---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "amundsen.fullname" . }}-test
  labels:
    app: {{ template "amundsen.name" . }}
    component: test
    chart: {{ template "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "amundsen.name" . }}
      component: test
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      {{- with default .Values.podAnnotations .Values.frontEnd.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
      labels:
        app: {{ template "amundsen.name" . }}
        component: test
        release: {{ .Release.Name }}
    spec:
      {{- with default .Values.nodeSelector .Values.frontEnd.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.frontEnd.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.frontEnd.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
    {{- if .Values.frontEnd.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.frontEnd.imagePullSecrets | indent 8 }}
    {{- end }}
      containers:
      - name: amundsen-test
        image: nginx:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: edp-airflow-pipe
                key: profiles_aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: edp-airflow-pipe
                key: profiles_aws_secret_access_key
        {{- with .Values.amundsentest.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
